//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewelery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ad()
        {
            this.AdImages = new HashSet<AdImage>();
            this.Wishlists = new HashSet<Wishlist>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int UserId { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public Nullable<int> MenuId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<int> SubSubCategoryId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> GoldCarat { get; set; }
        public Nullable<decimal> DiamondCarat { get; set; }
        public System.DateTime PublishDate { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public byte Status { get; set; }
        public Nullable<int> Reviews { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdImage> AdImages { get; set; }
        public virtual Category Category { get; set; }
        public virtual MenuItem MenuItem { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual SubSubCategory SubSubCategory { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wishlist> Wishlists { get; set; }
    }
}
