//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;

namespace Jewelery.Models
{
    using System;

    
    public partial class JeweleryEntities : DbContext
    {
        public class JeweleryDbContext : DbContext
        {
            public JeweleryDbContext(DbContextOptions<JeweleryDbContext> options)
                : base(options)
            {
            }

            public DbSet<AdImage> AdImages { get; set; }
            public DbSet<Ad> Ads { get; set; }
            public DbSet<Category> Categories { get; set; }
            public DbSet<CategoryLanguage> CategoryLanguages { get; set; }
            public DbSet<Language> Languages { get; set; }
            public DbSet<MenuItemLanguage> MenuItemLanguages { get; set; }
            public DbSet<MenuItem> MenuItems { get; set; }
            public DbSet<SubCategory> SubCategories { get; set; }
            public DbSet<SubCategoryLanguage> SubCategoryLanguages { get; set; }
            public DbSet<SubSubCategory> SubSubCategories { get; set; }
            public DbSet<SubSubCategoryLanguage> SubSubCategoryLanguages { get; set; }
            public DbSet<User> Users { get; set; }
            public DbSet<database_firewall_rules> database_firewall_rules { get; set; }
            public DbSet<Wishlist> Wishlists { get; set; }
            public DbSet<Message> Messages { get; set; }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                
            }
        }
    }
}
