//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jewelery.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jewelery.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abunə olun.
        /// </summary>
        public static string Abunə_olun {
            get {
                return ResourceManager.GetString("Abunə olun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad və Soyad.
        /// </summary>
        public static string Ad_və_Soyad {
            get {
                return ResourceManager.GetString("Ad və Soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız və Soyadınız.
        /// </summary>
        public static string Adınız_və_Soyadınız {
            get {
                return ResourceManager.GetString("Adınız və Soyadınız", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Səhifə.
        /// </summary>
        public static string AnaSehife {
            get {
                return ResourceManager.GetString("AnaSehife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtarış.
        /// </summary>
        public static string Axtarış {
            get {
                return ResourceManager.GetString("Axtarış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Söz və ya Kod ilə axtarış edin.
        /// </summary>
        public static string Axtarış_edin {
            get {
                return ResourceManager.GetString("Axtarış_edin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtarışın nəticəsi yoxdur!.
        /// </summary>
        public static string Axtarışın_nəticəsi_yoxdur_ {
            get {
                return ResourceManager.GetString("Axtarışın nəticəsi yoxdur!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to azdan çoxa.
        /// </summary>
        public static string azdan_çoxa {
            get {
                return ResourceManager.GetString("azdan çoxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağla.
        /// </summary>
        public static string Bağla {
            get {
                return ResourceManager.GetString("Bağla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baxış sayı.
        /// </summary>
        public static string Baxış_sayı {
            get {
                return ResourceManager.GetString("Baxış sayı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizimlə Əlaqə.
        /// </summary>
        public static string Bizimlə_Əlaqə {
            get {
                return ResourceManager.GetString("Bizimlə Əlaqə", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu elan Admin tərəfindən təsdiq üçün gözləyir..
        /// </summary>
        public static string Bu_elan_Admin_tərəfindən_təsdiq_üçün_gözləyir_ {
            get {
                return ResourceManager.GetString("Bu elan Admin tərəfindən təsdiq üçün gözləyir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu elan silinmişdir..
        /// </summary>
        public static string Bu_elan_silinmişdir_ {
            get {
                return ResourceManager.GetString("Bu elan silinmişdir.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çəki.
        /// </summary>
        public static string Çəki {
            get {
                return ResourceManager.GetString("Çəki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cəmi.
        /// </summary>
        public static string Cəmi {
            get {
                return ResourceManager.GetString("Cəmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıxış.
        /// </summary>
        public static string Çıxış {
            get {
                return ResourceManager.GetString("Çıxış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to çoxdan aza.
        /// </summary>
        public static string çoxdan_aza {
            get {
                return ResourceManager.GetString("çoxdan aza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daha çox.
        /// </summary>
        public static string Daha_çox {
            get {
                return ResourceManager.GetString("Daha çox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil ol.
        /// </summary>
        public static string Daxil_ol {
            get {
                return ResourceManager.GetString("Daxil ol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktiv et.
        /// </summary>
        public static string Deaktiv_et {
            get {
                return ResourceManager.GetString("Deaktiv et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Poçt.
        /// </summary>
        public static string E_Poçt {
            get {
                return ResourceManager.GetString("E-Poçt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Poçt ünvanı.
        /// </summary>
        public static string E_Poçt_ünvanı {
            get {
                return ResourceManager.GetString("E-Poçt ünvanı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elan başlığı.
        /// </summary>
        public static string Elan_başlığı {
            get {
                return ResourceManager.GetString("Elan başlığı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ELAN NƏTICƏLƏRI.
        /// </summary>
        public static string ELAN_NƏTICƏLƏRI {
            get {
                return ResourceManager.GetString("ELAN NƏTICƏLƏRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elan Yerləşdir.
        /// </summary>
        public static string Elan_Yerləşdir {
            get {
                return ResourceManager.GetString("Elan Yerləşdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elana bax.
        /// </summary>
        public static string Elana_bax {
            get {
                return ResourceManager.GetString("Elana bax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elanı seçilmiş etdiniz!.
        /// </summary>
        public static string Elanı_seçilmiş_etdiniz {
            get {
                return ResourceManager.GetString("Elanı seçilmiş etdiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elanı yerləşdir.
        /// </summary>
        public static string Elanı_yerləşdir {
            get {
                return ResourceManager.GetString("Elanı yerləşdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elanınız təsdiq üçün göndərildi. Admin təsdiq etdikdən sonra, saytda dərc olunacaqdır..
        /// </summary>
        public static string Elanınız_təsdiq_üçün_göndərildi__Admin_təsdiq_etdikdən_sonra__saytda_dərc_olunacaqdır_ {
            get {
                return ResourceManager.GetString("Elanınız təsdiq üçün göndərildi. Admin təsdiq etdikdən sonra, saytda dərc olunaca" +
                        "qdır.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elanlar.
        /// </summary>
        public static string Elanlar {
            get {
                return ResourceManager.GetString("Elanlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əlaqə.
        /// </summary>
        public static string Əlaqə {
            get {
                return ResourceManager.GetString("Əlaqə", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əlaqə Məlumatları.
        /// </summary>
        public static string Əlaqə_Məlumatları {
            get {
                return ResourceManager.GetString("Əlaqə Məlumatları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əlaqə.
        /// </summary>
        public static string Əlaqə2 {
            get {
                return ResourceManager.GetString("Əlaqə2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ƏN ÇOX BAXILANLAR.
        /// </summary>
        public static string ƏN_ÇOX_BAXILANLAR {
            get {
                return ResourceManager.GetString("ƏN ÇOX BAXILANLAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endirimli Məhsullar.
        /// </summary>
        public static string Endirimli_Məhsullar {
            get {
                return ResourceManager.GetString("Endirimli Məhsullar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ətraflı axtarış.
        /// </summary>
        public static string Ətraflı_axtarış {
            get {
                return ResourceManager.GetString("Ətraflı axtarış", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əyar.
        /// </summary>
        public static string Əyar {
            get {
                return ResourceManager.GetString("Əyar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.A.Q..
        /// </summary>
        public static string F_A_Q_ {
            get {
                return ResourceManager.GetString("F.A.Q.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtr et.
        /// </summary>
        public static string Filtr_et {
            get {
                return ResourceManager.GetString("Filtr et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Giriş {
            get {
                return ResourceManager.GetString("Giriş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göndər.
        /// </summary>
        public static string Göndər {
            get {
                return ResourceManager.GetString("Göndər", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hamısına baxın.
        /// </summary>
        public static string Hamısına_baxın {
            get {
                return ResourceManager.GetString("Hamısına baxın", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınız varsa buradan daxil olun.
        /// </summary>
        public static string Hesabınız_varsa_buradan_daxil_olun {
            get {
                return ResourceManager.GetString("Hesabınız varsa buradan daxil olun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabınız yoxdursa qeydiyyatdan keçin.
        /// </summary>
        public static string Hesabınız_yoxdursa_qeydiyyatdan_keçin {
            get {
                return ResourceManager.GetString("Hesabınız yoxdursa qeydiyyatdan keçin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ilə işarə edilmiş xanalar mütləq doldurulmalıdır.
        /// </summary>
        public static string ilə_işarə_edilmiş_xanalar_mütləq_doldurulmalıdır {
            get {
                return ResourceManager.GetString("ilə işarə edilmiş xanalar mütləq doldurulmalıdır", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlənmiş.
        /// </summary>
        public static string İşlənmiş {
            get {
                return ResourceManager.GetString("İşlənmiş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadə edilmiş.
        /// </summary>
        public static string İstifadə_edilmiş {
            get {
                return ResourceManager.GetString("İstifadə edilmiş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi.
        /// </summary>
        public static string İstifadəçi {
            get {
                return ResourceManager.GetString("İstifadəçi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi Razılaşması.
        /// </summary>
        public static string İstifadəçi_Razılaşması {
            get {
                return ResourceManager.GetString("İstifadəçi Razılaşması", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi razılaşmasını qəbul edirəm.
        /// </summary>
        public static string İstifadəçi_razılaşmasını_qəbul_edirəm {
            get {
                return ResourceManager.GetString("İstifadəçi razılaşmasını qəbul edirəm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi və ya Mağaza adı.
        /// </summary>
        public static string İstifadəçi_və_ya_Mağaza_adı {
            get {
                return ResourceManager.GetString("İstifadəçi və ya Mağaza adı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçinin bütün elanları.
        /// </summary>
        public static string İstifadəçinin_bütün_elanları {
            get {
                return ResourceManager.GetString("İstifadəçinin bütün elanları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kateqoriyanı seçin.
        /// </summary>
        public static string Kateqoriyanı_seçin {
            get {
                return ResourceManager.GetString("Kateqoriyanı seçin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keçidlər.
        /// </summary>
        public static string Keçidlər {
            get {
                return ResourceManager.GetString("Keçidlər", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kişilər üçün.
        /// </summary>
        public static string Kişilər_üçün {
            get {
                return ResourceManager.GetString("Kişilər üçün", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod.
        /// </summary>
        public static string Kod {
            get {
                return ResourceManager.GetString("Kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsul haqqında məlumatlar.
        /// </summary>
        public static string Məhsul_haqqında_məlumatlar {
            get {
                return ResourceManager.GetString("Məhsul haqqında məlumatlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsulu seçin.
        /// </summary>
        public static string Məhsulu_seçin {
            get {
                return ResourceManager.GetString("Məhsulu seçin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsulun kodu.
        /// </summary>
        public static string Məhsulun_kodu {
            get {
                return ResourceManager.GetString("Məhsulun kodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsulun vəziyyəti.
        /// </summary>
        public static string Məhsulun_vəziyyəti {
            get {
                return ResourceManager.GetString("Məhsulun vəziyyəti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat.
        /// </summary>
        public static string Məlumat {
            get {
                return ResourceManager.GetString("Məlumat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mənim Elanlarım.
        /// </summary>
        public static string MƏNIM_ELANLARIM {
            get {
                return ResourceManager.GetString("MƏNIM ELANLARIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menyu.
        /// </summary>
        public static string Menyu {
            get {
                return ResourceManager.GetString("Menyu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Başlığı.
        /// </summary>
        public static string Mesaj_Başlığı {
            get {
                return ResourceManager.GetString("Mesaj Başlığı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj Mətni.
        /// </summary>
        public static string Mesaj_Mətni {
            get {
                return ResourceManager.GetString("Mesaj Mətni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız Göndərildi.
        /// </summary>
        public static string Mesajınız_Göndərildi {
            get {
                return ResourceManager.GetString("Mesajınız Göndərildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil Nömrə.
        /// </summary>
        public static string Mobil_Nömrə {
            get {
                return ResourceManager.GetString("Mobil Nömrə", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OXŞAR ELANLAR.
        /// </summary>
        public static string OXŞAR_ELANLAR {
            get {
                return ResourceManager.GetString("OXŞAR ELANLAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qadınlar üçün.
        /// </summary>
        public static string Qadınlar_üçün {
            get {
                return ResourceManager.GetString("Qadınlar üçün", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qanunvericilik.
        /// </summary>
        public static string Qanunvericilik {
            get {
                return ResourceManager.GetString("Qanunvericilik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qaş.
        /// </summary>
        public static string Qaş {
            get {
                return ResourceManager.GetString("Qaş", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qaş tipini seçin.
        /// </summary>
        public static string Qaş_tipini_seçin {
            get {
                return ResourceManager.GetString("Qaş tipini seçin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qaşın ölçüsü.
        /// </summary>
        public static string Qaşın_ölçüsü {
            get {
                return ResourceManager.GetString("Qaşın ölçüsü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qeydiyyat.
        /// </summary>
        public static string Qeydiyyat {
            get {
                return ResourceManager.GetString("Qeydiyyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qısa Məlumat.
        /// </summary>
        public static string Qısa_Məlumat {
            get {
                return ResourceManager.GetString("Qısa Məlumat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qiymət.
        /// </summary>
        public static string Qiymət {
            get {
                return ResourceManager.GetString("Qiymət", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qızıl.
        /// </summary>
        public static string Qızıl {
            get {
                return ResourceManager.GetString("Qızıl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qızılın Dəyəri.
        /// </summary>
        public static string Qızılın_Dəyəri {
            get {
                return ResourceManager.GetString("Qızılın Dəyəri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qr.
        /// </summary>
        public static string qr__qram_ {
            get {
                return ResourceManager.GetString("qr (qram)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redaktə et.
        /// </summary>
        public static string Redaktə_et {
            get {
                return ResourceManager.GetString("Redaktə et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş elanlar.
        /// </summary>
        public static string Seçilmiş_elanlar {
            get {
                return ResourceManager.GetString("Seçilmiş elanlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmiş et.
        /// </summary>
        public static string Seçilmiş_et {
            get {
                return ResourceManager.GetString("Seçilmiş et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seçin.
        /// </summary>
        public static string seçin {
            get {
                return ResourceManager.GetString("seçin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şəkilləri seçin.
        /// </summary>
        public static string Şəkilləri_seçin {
            get {
                return ResourceManager.GetString("Şəkilləri seçin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şəxsi Kabinet.
        /// </summary>
        public static string Şəxsi_Kabinet {
            get {
                return ResourceManager.GetString("Şəxsi Kabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şəxsi Məlumatlar.
        /// </summary>
        public static string Şəxsi_Məlumatlar {
            get {
                return ResourceManager.GetString("Şəxsi Məlumatlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrə.
        /// </summary>
        public static string Şifrə {
            get {
                return ResourceManager.GetString("Şifrə", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrə təkrarı.
        /// </summary>
        public static string Şifrə_təkrarı {
            get {
                return ResourceManager.GetString("Şifrə təkrarı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıralama.
        /// </summary>
        public static string Sıralama {
            get {
                return ResourceManager.GetString("Sıralama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizin dərc etdiyiniz elan yoxdur. Yeni elan üçün buraya klik edin!.
        /// </summary>
        public static string Sizin_dərc_etdiyiniz_elan_yoxdur__Yeni_elan_üçün_buraya_klik_edin_ {
            get {
                return ResourceManager.GetString("Sizin dərc etdiyiniz elan yoxdur. Yeni elan üçün buraya klik edin!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SON ƏLAVƏ OLUNANLAR.
        /// </summary>
        public static string SON_ƏLAVƏ_OLUNANLAR {
            get {
                return ResourceManager.GetString("SON ƏLAVƏ OLUNANLAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorğunun göndərilməsində xəta baş verdi..
        /// </summary>
        public static string Sorğunun_göndərilməsində_xəta_baş_verdi_ {
            get {
                return ResourceManager.GetString("Sorğunun göndərilməsində xəta baş verdi.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorğunuz müvəffəqiyyətlə göndərildi.
        /// </summary>
        public static string Sorğunuz_müvəffəqiyyətlə_göndərildi {
            get {
                return ResourceManager.GetString("Sorğunuz müvəffəqiyyətlə göndərildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sot.
        /// </summary>
        public static string sot {
            get {
                return ResourceManager.GetString("sot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarix.
        /// </summary>
        public static string Tarix {
            get {
                return ResourceManager.GetString("Tarix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarixə görə.
        /// </summary>
        public static string Tarixə_görə {
            get {
                return ResourceManager.GetString("Tarixə görə", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TƏNZIMLƏMƏLƏR.
        /// </summary>
        public static string TƏNZIMLƏMƏLƏR {
            get {
                return ResourceManager.GetString("TƏNZIMLƏMƏLƏR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təsdiqlə.
        /// </summary>
        public static string Təsdiqlə {
            get {
                return ResourceManager.GetString("Təsdiqlə", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipi seçin.
        /// </summary>
        public static string Tipi_seçin {
            get {
                return ResourceManager.GetString("Tipi seçin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uğurlu!.
        /// </summary>
        public static string Uğurlu_ {
            get {
                return ResourceManager.GetString("Uğurlu!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ümumi.
        /// </summary>
        public static string Ümumi {
            get {
                return ResourceManager.GetString("Ümumi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvan.
        /// </summary>
        public static string Ünvan {
            get {
                return ResourceManager.GetString("Ünvan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uşaqlar üçün.
        /// </summary>
        public static string Uşaqlar_üçün {
            get {
                return ResourceManager.GetString("Uşaqlar üçün", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vəziyyət.
        /// </summary>
        public static string Vəziyyət {
            get {
                return ResourceManager.GetString("Vəziyyət", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xəta!.
        /// </summary>
        public static string Xəta_ {
            get {
                return ResourceManager.GetString("Xəta!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni.
        /// </summary>
        public static string Yeni {
            get {
                return ResourceManager.GetString("Yeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Elan Yerləşdir.
        /// </summary>
        public static string Yeni_Elan_Yerləşdir {
            get {
                return ResourceManager.GetString("Yeni Elan Yerləşdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zəng et.
        /// </summary>
        public static string Zəng_et {
            get {
                return ResourceManager.GetString("Zəng et", resourceCulture);
            }
        }
    }
}
